### ISSUE TITLE
Compilação

### ISSUE THREAD

**Issue by silfar** [lucascience/protheus-docker#1]
Lucas parabens pelo trabalho, vc poderia me ajudar como eu faria para compilar programas, pois quando vou fazer a compilação ele diz que não pode obter a trava exclusiva como se algum estivesse usando o RPO

**Comment by lucasrodrigues85** [comment]
Olá, boa tarde!

Obrigado pelo feedback!

Quanto a compilação, se não tiver nenhum usuário logado no ambiente, a compilação deverá funcionar. Lembrando que você deverá apontar no VSCode os dados do container (IP, porta, etc). Subindo de forma padrão, você poderá usar localhost e a porta 6000.

Na configuração que enviei como exemplo, existe a chave [HTTP], que possivelmente possa estar causando o erro na sua tentativa. Tente comentá-la, inserindo um ; antes da chave (ex. abaixo):

```
;[HTTP]
Port=8100
Enable=1
Path=/protheus_data/help_online
Environment=protheus
```

A mensagem de acesso exclusivo é apresentada caso exista algum usuário conectado ao appserver ou algum job, schedule e threads (normalmente webservices SOAP e REST) presentes no appserver. Neste caso, como há um serviço HTTP configurado, causará a falha no acesso exclusivo.
